language: node_js
node_js:
  - stable
branches:
  only:
    - master
    - develop
before_script:
  - npm install @angular/cli
script:
   - ng build --prod
notifications:
  email:
    on_success: never
    on_failure: always
